# Generated by Django 2.2.5 on 2020-06-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital_call', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinvestment',
            name='investment_amount',
            field=models.DecimalField(decimal_places=2, default=15000000, max_digits=10),
            preserve_default=False,
        ),
    ]
