# Generated by Django 2.2.5 on 2020-06-06 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capital_call', '0002_fundinvestment_investment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinvestment',
            name='call',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='capital_call.Call'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundinvestment',
            name='commitment',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='capital_call.Commitment'),
            preserve_default=False,
        ),
    ]
