# Generated by Django 2.2.5 on 2020-06-06 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capital_call', '0003_auto_20200606_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundinvestment',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calls', to='capital_call.Call'),
        ),
        migrations.AlterField(
            model_name='fundinvestment',
            name='commitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='capital_call.Commitment'),
        ),
    ]
